service: borrowmyrescue-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  borrowersAndDogs:
    handler: borrowmyrescue.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
# events for the dog list
      - http:
          path: dogs
          method: get
          cors: true
      - http:
          path: dogs
          method: post
          cors: true
      - http:
          path: dogs/{dogId}
          method: delete
          cors: true
      - http:
          path: dogs/{dogId}
          method: put
          cors: true
# events for borrowers list
      - http:
          path: borrowers
          method: get
          cors: true
      - http:
          path: borrowers
          method: post
          cors: true
      - http:
          path: borrowers/{borrowerId}
          method: delete
          cors: true
      - http:
          path: borrowers/{borrowerId}
          method: put
          cors: true