service: borrowmyrescue-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  borrowersAndDogs:
    handler: borrowmyrescue.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
# events for the dog list
      - http:
          path: dogs
          method: get
          cors: true
      - http:
          path: dogs
          method: post
          cors: true
      - http:
          path: dogs/{dogId}
          method: delete
          cors: true
      - http:
          path: dogs/{dogId}
          method: put
          cors: true
# events for borrowers list
      - http:
          path: borrowers
          method: get
          cors: true
      - http:
          path: borrowers
          method: post
          cors: true
      - http:
          path: borrowers/{borrowerId}
          method: delete
          cors: true
      - http:
          path: borrowers/{borrowerId}
          method: put
          cors: true
# events for matching dog to borrowers
# find possible matching borrowers for dogId selected
      - http:
          path: matching/{dogId}
          method: get
          cors: true   
# post borrower/dog/day combination to Borrowers_Dogs table
      - http:
          path: matching
          method: post
          cors: true
# events for dog ratings
# obtain dog name and average rating for all dogs
      - http:
          path: dogRatings
          method: get
          cors: true  
# post rating provided by borrower for the borrowed dog
      - http:
          path: dogRatings
          method: post
          cors: true